CREATE TABLE USERS
(
    username VARCHAR(50)  NOT NULL PRIMARY KEY,
    password VARCHAR(500) NOT NULL,
    enabled  BOOLEAN      NOT NULL
);

CREATE TABLE authorities
(
    username  VARCHAR(50) NOT NULL,
    authority VARCHAR(50) NOT NULL,
    CONSTRAINT fk_authorities_users FOREIGN KEY (username) REFERENCES USERS (username)
);
CREATE UNIQUE INDEX ix_auth_username ON authorities (username, authority);

CREATE TABLE CAT_PLACE_USER
(
    DISPLAY_NAME    VARCHAR(50)        NOT NULL,
    username        VARCHAR(50) UNIQUE NOT NULL PRIMARY KEY,
    BIO             VARCHAR(1024)       DEFAULT '',
    PROFILE_PICTURE BINARY LARGE OBJECT DEFAULT NULL,
    EMAIL           VARCHAR(50)         DEFAULT NULL,
    ROLES           VARCHAR(50) ARRAY DEFAULT NULL
    --CONSTRAINT fk_cat_place_users FOREIGN KEY (username) REFERENCES USERS (username) removed because of tests, should be used in prod
);

CREATE TABLE cat
(
    ID              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL UNIQUE,
    NAME            VARCHAR(32)                                         NOT NULL,
    DATE_OF_BIRTH   TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    OWNER           VARCHAR(50)                                         NOT NULL,
    PROFILE_PICTURE BINARY LARGE OBJECT      DEFAULT NULL,
    BIO             VARCHAR(1024)            DEFAULT '',
    IS_ALIVE        BOOLEAN                                             NOT NULL,
    CONSTRAINT fk_cat_owners FOREIGN KEY (OWNER) REFERENCES CAT_PLACE_USER (username)
);


-- I know this is ugly and memory inefficient, having 2 tables for users, but, I wanted to store all those extra things, and I was using an InMemoryUserDetailsManager,
-- and I wanted to switch to a JdbcUserDetailsManager, but I just couldnt get it to work with more values in one table; it isn't meant for that anyway.
-- I could not find any resources on how to make a custom details manager that does what I want(has test users, stored in db, can be accessed for purposes other than authentication) and works,
-- If you know how please contact me, discord is legoaggelos.


CREATE TABLE POST
(
    ID          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL UNIQUE,
    IMAGE       BINARY LARGE OBJECT                                 NOT NULL,
    LIKE_COUNT  BIGINT                                                       DEFAULT 0,
    CAT_OWNER   BIGINT                                              NOT NULL,
    USER_OWNER  VARCHAR(50)                                         NOT NULL,
    DESC        VARCHAR(4096)                                       NOT NULL DEFAULT '',
    UPLOAD_DATE TIMESTAMP WITH TIME ZONE                            NOT NULL,
    IS_APPROVED BOOLEAN                                                      DEFAULT UNKNOWN,
    CONSTRAINT fk_post_posters_cat_place_users FOREIGN KEY (user_owner) REFERENCES CAT_PLACE_USER (username),
    CONSTRAINT fk_post_cat_poster_cat FOREIGN KEY (cat_owner) REFERENCES cat (ID)
);

CREATE TABLE COMMENT
(
    ID              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL UNIQUE,
    CONTENT         VARCHAR(1024)                                       NOT NULL,
    LIKE_COUNT      BIGINT DEFAULT 0,
    POST_ID         BIGINT                                              NOT NULL,
    POSTER          VARCHAR(50)                                         NOT NULL, --the one who posted the comment
    POST_USER_POSTER     VARCHAR(50)                                         NOT NULL, --the one who posted the post the comment belongs in
    POST_CAT_POSTER BIGINT                                              NOT NULL, --the cat who posted the post the comment belongs in
    POST_TIME       TIMESTAMP WITH TIME ZONE                            NOT NULL,
    REPLYING_TO     BIGINT DEFAULT NULL,                                           --null = not a reply!
    CONSTRAINT fk_post_user_posters_cat_place_users FOREIGN KEY (post_user_poster) REFERENCES CAT_PLACE_USER (username),
    CONSTRAINT fk_comment_in_post_cat_poster_cat FOREIGN KEY (post_cat_poster) REFERENCES cat (ID),
    CONSTRAINT fk_comment_posters_cat_place_users FOREIGN KEY (poster) REFERENCES CAT_PLACE_USER (username),
    CONSTRAINT fk_post_id_comment FOREIGN KEY (POST_ID) REFERENCES POST(ID)
    --no replying to because of default and recursive requirement
);

CREATE TABLE liked_post
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL UNIQUE,
    username   VARCHAR(50)                                         NOT NULL,
    post_liked_id BIGINT                                              NOT NULL,
    CONSTRAINT FK_liked_posts_users FOREIGN KEY (username) REFERENCES CAT_PLACE_USER (username),
    CONSTRAINT FK_liked_posts_ids FOREIGN KEY (post_liked_id) REFERENCES POST (ID)
);

CREATE TABLE liked_comment
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL UNIQUE,
    username      VARCHAR(50)                                         NOT NULL,
    comment_liked_id BIGINT                                              NOT NULL,
    CONSTRAINT FK_liked_comments_users FOREIGN KEY (username) REFERENCES CAT_PLACE_USER (username),
    CONSTRAINT FK_liked_comments_ids FOREIGN KEY (comment_liked_id) REFERENCES COMMENT (ID)
);