INSERT INTO CAT(ID, NAME, AGE_IN_MONTHS, OWNER, PROFILE_PICTURE) VALUES (5, 'psilos', 4, 'legoaggelos', null);
INSERT INTO CAT(ID, NAME, AGE_IN_MONTHS, OWNER, PROFILE_PICTURE) VALUES (6, 'kontos', 69, 'legoaggelos', null);
INSERT INTO CAT(ID, NAME, AGE_IN_MONTHS, OWNER, PROFILE_PICTURE) VALUES (3, 'mesos', 31, 'legoaggelos', null);
INSERT INTO CAT(ID, NAME, AGE_IN_MONTHS, OWNER, PROFILE_PICTURE) VALUES (4, 'arabas', 1, 'kat', null);